apiVersion: v2
name: static-file-server
description: A Helm chart for lightweight static file server with modern directory listing UI
type: application
version: 0.4.0
appVersion: "v0.4.0"

kubeVersion: ">=1.16.0-0"

keywords:
  - static
  - file-server
  - web
  - directory-listing
  - lightweight

home: https://github.com/somaz94/static-file-server
sources:
  - https://github.com/somaz94/static-file-server

maintainers:
  - name: somaz94
    url: https://github.com/somaz94
